subdirs = \
    upipe \
    upipe-alsa \
    upipe-amt \
    upipe-av \
    upipe-bearssl \
    upipe-blackmagic \
    upipe-dvb \
    upipe-dvbcsa \
    upipe-dveo \
    upipe-ebur128 \
    upipe-filters \
    upipe-framers \
    upipe-freetype \
    upipe-gl \
    upipe-hbrmt \
    upipe-hls \
    upipe-modules \
    upipe-netmap \
    upipe-openssl \
    upipe-osx \
    upipe-pcap \
    upipe-pthread \
    upipe-speexdsp \
    upipe-swresample \
    upipe-swscale \
    upipe-ts \
    upipe-v210 \
    upipe-x264 \
    upipe-x265 \
    upipe-zvbi \
    upump-ecore \
    upump-ev \
    upump-srt
