#ifndef __HW_FLAGS_H
#define __HW_FLAGS_H

/* xo */
#define XO_148P50MHZ_SEL 0
#define XO_148P35MHZ_SEL 1

/* refclk */
#define REFCLK0_SEL (1<<0)
#define REFCLK1_SEL (1<<1)

/* spi */
#define SPI_CTRL_START 0x1
#define SPI_CTRL_LENGTH (1<<8)
#define SPI_STATUS_DONE 0x1

/* pcie */
#define DMA_TABLE_LOOP_INDEX (1 << 0)
#define DMA_TABLE_LOOP_COUNT (1 << 16)

/* sdi */
#define SDI_UNDEF_RATE   0
#define SDI_PAL_RATE     1
#define SDI_NTSC_RATE    2
#define SDI_GENLOCK_RATE 3

#define SDI_TX_MODE_HD 0b00
#define SDI_TX_MODE_SD 0b01
#define SDI_TX_MODE_3G 0b10

#define SDI_TX_PI_ENABLE  (1 << 0)
#define SDI_TX_PI_STEP    (1 << 1)
#define SDI_TX_PI_INC_DEC (1 << 5)

#define SDI_LOOPBACK_NEAR_END_PCS 0b001
#define SDI_LOOPBACK_NEAR_END_PMA 0b010
#define SDI_LOOPBACK_FAR_END_PMA  0b100
#define SDI_LOOPBACK_FAR_END_PCS  0b110

#define SDI_RX_LOCK_CORE     (1<<0)
#define SDI_RX_LOCK_DATAPATH (1<<1)

#define SDI_CAP_HAS_VCXOS 1
#define SDI_CAP_HAS_GS12241 2
#define SDI_CAP_HAS_GS12281 4
#define SDI_CAP_HAS_SI5324 8
#define SDI_CAP_HAS_GENLOCK 16
#define SDI_CAP_HAS_LMH0387 32
#define SDI_CAP_HAS_SI596 64
#define SDI_CAP_HAS_SI552 128
#define SDI_CAP_DUO2 (SDI_CAP_HAS_LMH0387)
#define SDI_CAP_MINI_4K (SDI_CAP_HAS_SI596)
#define SDI_CAP_SDI_4K (SDI_CAP_HAS_SI552)
#define SDI_CAP_FALCON9 (SDI_CAP_HAS_VCXOS | SDI_CAP_HAS_GS12241 | SDI_CAP_HAS_GS12281 | SDI_CAP_HAS_SI5324 | SDI_CAP_HAS_GENLOCK)

#endif /* __HW_FLAGS_H */
